name:                maths
version:             0.1.0.0
github:              "totherme/maths"
license:             BSD3
author:              "Gareth Smith"
maintainer:          "github@totherme.org"
copyright:           "2018 Gareth Smith"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/totherme/maths#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2.1
- unfoldable
library:
  source-dirs: src

tests:
  maths-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maths
    - QuickCheck
    - hspec >= 2.4.3
